export const UPDATE_EVENTS = "UPDATE_EVENTS";

export const ADD_TO_SIDEBAR = "ADD_TO_SIDEBAR";
export const REMOVE_FROM_SIDEBAR = "REMOVE_FROM_SIDEBAR";
export const TOGGLE_SIDEBAR = "TOGGLE_SIDEBAR";

export const UPDATE_CATEGORIES = "UPDATE_CATEGORIES";
export const UPDATE_CURRENT_CATEGORY = "UPDATE_CURRENT_CATEGORY";
